# -*- coding: utf-8 -*-
"""Intelligent Road Safety Vision System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1esD0OxLY18KGZiNKQenWR8fmaPlK-Rb5
"""

# AICTE Shell Edunet Internship | Author: Sharlene Anna Pereira | Week 1

# Dependencies
!pip install ultralytics opencv-python matplotlib torch --quiet

# Libraries
from ultralytics import YOLO
import cv2
import os

#  YOLOv8 Pretrained Model
# 'yolov8n.pt' is a lightweight model (fast & accurate)
model = YOLO("yolov8n.pt")

# Input Files
IMAGE_PATH = "road_scene.jpg"
VIDEO_PATH = "road_video.mp4"

# Image Detection
def detect_on_image(image_path):
    print(f"🔍 Detecting objects in image: {image_path}")
    results = model(image_path, show=True)
    output_path = os.path.splitext(image_path)[0] + "_result.jpg"
    results[0].save(output_path)
    print(f"✅ Detection complete! Saved at: {output_path}")

# Video Detection
def detect_on_video(video_path):
    print(f"🎥 Processing video: {video_path}")
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print("❌ Could not open video file.")
        return

    # Output video setup
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps = int(cap.get(cv2.CAP_PROP_FPS))

    output_filename = "road_video_result.mp4"
    out = cv2.VideoWriter(
        output_filename,
        cv2.VideoWriter_fourcc(*"mp4v"),
        fps,
        (width, height)
    )

    # Frame-by-frame processing
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # YOLOv8 detection
        results = model(frame, stream=True)
        for r in results:
            annotated_frame = r.plot()
            out.write(annotated_frame)

    cap.release()
    out.release()
    print(f"✅ Video processed successfully! Output saved as {output_filename}")

if __name__ == "__main__":
    print("🚦 Starting VisionGuard AI Detection System (Week 1)...")

    if os.path.exists(VIDEO_PATH):
        detect_on_video(VIDEO_PATH)
    elif os.path.exists(IMAGE_PATH):
        detect_on_image(IMAGE_PATH)
    else:
        print("⚠️ Please upload 'road_scene.jpg' or 'road_video.mp4' first.")