# -*- coding: utf-8 -*-
"""Week 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMxqQr6UF8RYqhA07WyqaktpRU2RhfcI
"""

# ===============================================================
# 🚗 AutoSafeDrive AI — Week 2 PRO (Fixed Annotation + Gradio)
# Zero-shot YOLOv8 on IDD + Risk Overlay + CSV + Gradio Demo
# ===============================================================

!pip install -q kagglehub ultralytics gradio opencv-python-headless pandas numpy matplotlib tqdm

import os, random, shutil, cv2, numpy as np, pandas as pd, matplotlib.pyplot as plt
from tqdm import tqdm
from ultralytics import YOLO
import kagglehub, gradio as gr
from datetime import datetime

# -------------------------
# 0) Paths & folders
# -------------------------
ROOT = "/content"
DATA_ROOT = os.path.join(ROOT, "data/idd")
OUT_DIR = os.path.join(ROOT, "autosafedrive_outputs")
os.makedirs(OUT_DIR, exist_ok=True)

for split in ["train","val","test"]:
    os.makedirs(os.path.join(DATA_ROOT, split, "images"), exist_ok=True)

# -------------------------
# 1) Load IDD via KaggleHub
# -------------------------
print("📦 Downloading Indian Driving Dataset (IDD) via KaggleHub...")
idd_path = kagglehub.dataset_download("mitanshuchakrawarty/new-idd-dataset")
print("✅ IDD path:", idd_path)

# Collect images
all_imgs = []
for root, _, files in os.walk(idd_path):
    for f in files:
        if f.lower().endswith((".jpg",".jpeg",".png")):
            all_imgs.append(os.path.join(root, f))

if len(all_imgs) == 0:
    raise RuntimeError("No images found inside the IDD dataset path. Please verify the Kaggle dataset contents.")

print(f"📸 Found {len(all_imgs)} images in IDD")

# -------------------------
# 2) Split into train/val/test (structure only)
# -------------------------
random.shuffle(all_imgs)
n = len(all_imgs)
train, val, test = np.split(all_imgs, [int(0.7*n), int(0.9*n)])

def copy_imgs(imgs, split):
    dst_dir = os.path.join(DATA_ROOT, split, "images")
    for p in tqdm(imgs, desc=f"Copying {split}"):
        shutil.copy(p, os.path.join(dst_dir, os.path.basename(p)))

# Copy a **small** subset to keep the notebook fast & light
copy_imgs(train[:200], "train")
copy_imgs(val[:50], "val")
copy_imgs(test[:50], "test")

print("✅ Split structure ready (subset copied for speed):",
      f"train={min(200,len(train))}, val={min(50,len(val))}, test={min(50,len(test))}")

# -------------------------
# 3) Load YOLOv8n (COCO-pretrained)
# -------------------------
model = YOLO("yolov8n.pt")
names = model.model.names  # id -> label

INTEREST = {"car","bus","truck","bicycle","motorcycle","person","traffic light"}
VULN = {"person","bicycle"}

# -------------------------
# 4) Risk helpers (robust)
# -------------------------
RISK_SAFE_MAX, RISK_CAUTION_MAX = 40, 70

def risk_color(r):
    return (0,200,0) if r<RISK_SAFE_MAX else (0,215,255) if r<RISK_CAUTION_MAX else (0,0,230)

def status_from_avg(a):
    return ("SAFE",(0,200,0)) if a<RISK_SAFE_MAX else ("CAUTION",(0,215,255)) if a<RISK_CAUTION_MAX else ("DANGER",(0,0,230))

def compute_risk_xyxy(box, H, cls_name):
    # Proximity from bbox height + small bonus for vulnerable classes
    y1, y2 = float(box[1]), float(box[3])
    prox = max(0.0, (y2 - y1) / max(1.0, H))
    risk = prox * 100.0
    if cls_name in VULN:
        risk += 10.0
    return float(np.clip(risk, 0, 100))

def draw_banner(img, text, color):
    pad=8
    (tw,th),_=cv2.getTextSize(text, cv2.FONT_HERSHEY_SIMPLEX, 0.8, 2)
    x1,y1=10,10; x2,y2=10+tw+2*pad, 10+th+2*pad
    cv2.rectangle(img, (x1,y1), (x2,y2), color, -1)
    cv2.putText(img, text, (x1+pad, y2-pad-2), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0,0,0), 2)

# -------------------------
# 5) Batch evaluate test split + annotate a few samples
# -------------------------
test_dir = os.path.join(DATA_ROOT, "test", "images")
test_imgs = sorted(os.listdir(test_dir))
records = []
annotated_samples = []

print("🔎 Running inference on test split...")
for i, fn in enumerate(tqdm(test_imgs, desc="Infer test")):
    path = os.path.join(test_dir, fn)
    img = cv2.imread(path)
    if img is None:
        continue

    res = model(img, conf=0.3, verbose=False)[0]
    risks = []

    if (res.boxes is not None) and (len(res.boxes) > 0):
        bx = res.boxes.xyxy.cpu().numpy()
        cl = res.boxes.cls.cpu().numpy().astype(int)
        cf = res.boxes.conf.cpu().numpy()

        for (x1,y1,x2,y2), cid, conf in zip(bx, cl, cf):
            cls = names.get(cid, str(cid))
            if cls not in INTEREST:
                continue
            r = compute_risk_xyxy([x1,y1,x2,y2], img.shape[0], cls)
            risks.append(r)

    avg_risk = float(np.mean(risks)) if len(risks) else 0.0
    status, color = status_from_avg(avg_risk)
    records.append({"image": fn, "avg_risk": round(avg_risk,2), "status": status})

    # Save annotation for first few samples
    if i < 6:
        vis = img.copy()
        if (res.boxes is not None) and (len(res.boxes) > 0):
            bx = res.boxes.xyxy.cpu().numpy()
            cl = res.boxes.cls.cpu().numpy().astype(int)
            cf = res.boxes.conf.cpu().numpy()

            for (x1,y1,x2,y2), cid, conf in zip(bx, cl, cf):
                cls = names.get(cid, str(cid))
                if cls not in INTEREST:
                    continue
                r = compute_risk_xyxy([x1,y1,x2,y2], vis.shape[0], cls)
                col = risk_color(r)
                x1i,y1i,x2i,y2i = map(int, [x1,y1,x2,y2])
                cv2.rectangle(vis, (x1i,y1i), (x2i,y2i), col, 2)
                cv2.putText(vis, f"{cls} {int(conf*100)}% | R{int(r)}%", (x1i, max(20,y1i-6)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, col, 2)

        draw_banner(vis, f"AVG RISK: {avg_risk:.1f}%  STATUS: {status}", color)
        outp = os.path.join(OUT_DIR, f"annotated_{i}_{fn}")
        cv2.imwrite(outp, vis)
        annotated_samples.append(outp)

df = pd.DataFrame(records)
csv_path = os.path.join(OUT_DIR, f"idd_eval_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv")
df.to_csv(csv_path, index=False)
print(f"✅ CSV saved: {csv_path}")

# Plot quick analytics
plt.figure(figsize=(6,4))
plt.hist(df["avg_risk"], bins=12, color="skyblue", edgecolor="k")
plt.title("Risk Distribution (Test Subset)")
plt.xlabel("Avg Risk (%)"); plt.ylabel("Count")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR,"risk_hist.png")); plt.close()

status_counts = df["status"].value_counts()
plt.figure(figsize=(5,4))
plt.bar(status_counts.index, status_counts.values, color=["green","orange","red"])
plt.title("Safety Status Distribution")
plt.tight_layout()
plt.savefig(os.path.join(OUT_DIR,"status_bar.png")); plt.close()

print("✅ Saved analytics plots to autosafedrive_outputs/")

# -------------------------
# 6) Gradio app (robust annotation)
# -------------------------
SAMPLES = annotated_samples  # pre-annotated examples
RAW_SAMPLES = [os.path.join(DATA_ROOT, "test", "images", fn) for fn in test_imgs[:12]]

def run_analysis(image):
    """Gradio handler: always annotate and return banner + metrics."""
    if image is None:
        return None, "Please upload an image or pick a sample.", 0.0, "NA"

    bgr = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR)
    res = model(bgr, conf=0.3, verbose=False)[0]
    avg_risk = 0.0
    vis = bgr.copy()
    risks = []

    if (res.boxes is not None) and (len(res.boxes) > 0):
        bx = res.boxes.xyxy.cpu().numpy()
        cl = res.boxes.cls.cpu().numpy().astype(int)
        cf = res.boxes.conf.cpu().numpy()

        for (x1,y1,x2,y2), cid, conf in zip(bx, cl, cf):
            cls = names.get(cid, str(cid))
            if cls not in INTEREST:
                continue
            r = compute_risk_xyxy([x1,y1,x2,y2], vis.shape[0], cls)
            risks.append(r)
            col = risk_color(r)
            x1i,y1i,x2i,y2i = map(int, [x1,y1,x2,y2])
            cv2.rectangle(vis, (x1i,y1i), (x2i,y2i), col, 2)
            cv2.putText(vis, f"{cls} {int(conf*100)}% | R{int(r)}%", (x1i, max(20,y1i-6)),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.6, col, 2)

    avg_risk = float(np.mean(risks)) if risks else 0.0
    status, color = status_from_avg(avg_risk)
    draw_banner(vis, f"AVG RISK: {avg_risk:.1f}%  STATUS: {status}", color)

    rgb = cv2.cvtColor(vis, cv2.COLOR_BGR2RGB)
    msg = f"**Status:** {status}\n**Avg Risk:** {avg_risk:.1f}%\nDetections: {len(risks)}"
    return rgb, msg, round(avg_risk,2), status

def load_sample(idx, use_annotated=True):
    """Load a guaranteed sample image for demo."""
    try:
        arr = SAMPLES if use_annotated and len(SAMPLES)>0 else RAW_SAMPLES
        idx = int(idx)
        idx = max(0, min(idx, len(arr)-1))
        img = cv2.imread(arr[idx])
        if img is None:
            return None
        return cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    except:
        return None

with gr.Blocks(title="AutoSafeDrive AI – Week 2 PRO (Fixed)") as demo:
    gr.Markdown("## 🚗 AutoSafeDrive AI — Week 2 PRO\n**Zero-shot YOLOv8 + IDD + Risk Overlay + CSV + Gradio.**\nPick an IDD sample or upload your own image. The annotation is robust and always drawn if detections exist.")

    with gr.Row():
        sample_idx = gr.Slider(0, max(0,len(RAW_SAMPLES)-1), step=1, value=0, label="IDD Sample Index")
        pick_raw = gr.Button("Load Raw IDD Sample")
        pick_anno = gr.Button("Load Pre-annotated Sample")
    img_in = gr.Image(label="Input Road Image", type="pil")
    run_btn = gr.Button("Analyze", variant="primary")

    with gr.Row():
        img_out = gr.Image(label="Annotated Output")
        md = gr.Markdown()
    with gr.Row():
        risk_num = gr.Number(label="Avg Risk (%)", precision=2)
        status_txt = gr.Textbox(label="Status")

    with gr.Row():
        gr.Markdown(f"CSV: `{os.path.basename(csv_path)}` saved in `autosafedrive_outputs/`")
    with gr.Row():
        gr.Image(label="Risk Histogram", value=os.path.join(OUT_DIR,"risk_hist.png"))
        gr.Image(label="Status Distribution", value=os.path.join(OUT_DIR,"status_bar.png"))

    pick_raw.click(fn=lambda i: load_sample(i, False), inputs=[sample_idx], outputs=[img_in])
    pick_anno.click(fn=lambda i: load_sample(i, True),  inputs=[sample_idx], outputs=[img_in])
    run_btn.click(fn=run_analysis, inputs=[img_in], outputs=[img_out, md, risk_num, status_txt])

demo.launch(share=True)

print("✅ Gradio launched. If you saw no boxes earlier, this build fixes it:")
print("   • Uses robust result handling (checks boxes exist)")
print("   • Draws RGB output for Gradio (correct colors)")
print("   • Includes guaranteed IDD samples to test instantly")
print(f"   • CSV & plots saved in: {OUT_DIR}")